-- Schema inicial da aplicacao de votacao.
-- SQL padrao compativel com H2 e PostgreSQL.

CREATE TABLE pauta (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo        VARCHAR(150) NOT NULL,
    descricao     VARCHAR(2000),
    data_criacao  TIMESTAMP    NOT NULL
);

CREATE TABLE sessao_votacao (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pauta_id        BIGINT    NOT NULL,
    data_abertura   TIMESTAMP NOT NULL,
    data_encerramento TIMESTAMP NOT NULL,
    CONSTRAINT fk_sessao_pauta FOREIGN KEY (pauta_id) REFERENCES pauta (id)
);

CREATE INDEX idx_sessao_pauta ON sessao_votacao (pauta_id);

CREATE TABLE voto (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sessao_id     BIGINT      NOT NULL,
    associado_id  VARCHAR(14) NOT NULL,
    opcao         VARCHAR(3)  NOT NULL,
    data_voto     TIMESTAMP   NOT NULL,
    CONSTRAINT fk_voto_sessao FOREIGN KEY (sessao_id) REFERENCES sessao_votacao (id),
    -- Garante no banco que cada associado vota no maximo uma vez por sessao/pauta
    CONSTRAINT uk_voto_sessao_associado UNIQUE (sessao_id, associado_id)
);

-- Indice usado pela contabilizacao (COUNT por opcao). Critico para performance
-- em cenarios com centenas de milhares de votos.
CREATE INDEX idx_voto_sessao_opcao ON voto (sessao_id, opcao);
